
# Rota raiz
GET http://127.0.0.1:8000/


# Documentation
###
GET http://127.0.0.1:8000/docs

#######################################
############  produto  ################
#######################################

# Criar produto
POST http://127.0.0.1:8000/produto HTTP/1.1
content-type: application/json

{
    "id": 2,
    "nome": "Tenis Balenciaga",
    "descricao": "Tenis sem alça Balenciaga",
    "preco": 11000.50
}

#####################################
# Buscar produto pelo id do produto
###
GET http://127.0.0.1:8000/produto/1 HTTP/1.1
content-type: application/json


#####################################
# Deletar produto pelo id do produto
###
DELETE http://127.0.0.1:8000/produto/5 HTTP/1.1
content-type: application/json