# Rota raiz
GET http://127.0.0.1:8000/

###
# Criar usuário
POST http://127.0.0.1:8000/api/users HTTP/1.1
content-type: application/json

{
    "name": "Luiza",
    "email": "lumagalu@gmail.com",
    "password": "123456",
    "is_active": "True",   
    "is_admin": "False"
}

###
# Buscar usuário pelo email
GET http://127.0.0.1:8000/users/lumagalu@gmail.com HTTP/1.1
content-type: application/json