# Rota raiz
GET http://127.0.0.1:8000/

###
# Criar usuário
POST http://127.0.0.1:8000/api/users/user HTTP/1.1
content-type: application/json

{
    "name": "Luiza",
    "email": "lumagalu@gmai.com",
    "password": "123456"
    
}

###
# Buscar usuário pelo email
GET http://127.0.0.1:8000/users/lumagalu@gmail.com HTTP/1.1
content-type: application/json