
# # Rota raiz
# GET http://127.0.0.1:8000/


# # Documentation
# ###
# GET http://127.0.0.1:8000/docs

# #######################################
# ############  produto  ################
# #######################################

# #Get all products
# GET http://127.0.0.1:8000/products/all
# content-type: application/json

# ###
# # Criar produto
# POST http://127.0.0.1:8000/product HTTP/1.1
# content-type: application/json

# {
#     "name": "JOIA TESTE",
#     "description": "JOIA TESTE",
#     "price": 11000.50,
#     "image": "TESTE",
#     "code": "8888",
#     "category": "joia",
#     "inventory": 30
    
# }
  
# #####################################
# # Buscar produto pelo código do produto
# ###
# GET http://127.0.0.1:8000/produto/002 HTTP/1.1
# content-type: application/json


# #####################################
# # Deletar produto pelo id do produto
# ###
# DELETE http://127.0.0.1:8000/produto/5 HTTP/1.1
# content-type: application/json